#if !defined __DEFINES__
#define __DEFINES__

#define NULL "\0"

#define GAMEMODE_TEXT "Drift Gamemode"
#define GAMEMODE_VERSION "1.0"


//MYSQL

#define MYSQL_HOST "127.0.0.1"
#define MYSQL_USER "root"
#define MYSQL_PASSWORD ""
#define MYSQL_DB_NAME "driftserver"

//Ranks

#define HEADADMIN_RANK 5
#define VHEAD_RANK 4
#define ADMIN_RANK 3
#define JADMIN_RANK 2
#define FRIEND_RANK 1
#define PLAYER_RANK 0
#define BANNED_PLAYER -1



#endif