#if !defined __DEFINES__
#define __DEFINES__

#define NULL "\0"

#define GAMEMODE_TEXT "Drift Gamemode"
#define GAMEMODE_VERSION "1.0"


//MYSQL

#define MYSQL_HOST "localhost"
#define MYSQL_USER "rot"
#define MYSQL_PASSWORD "rot"
#define MYSQL_DB_NAME "drift_server"

//Ranks

#define HEADADMIN_RANK 5
#define VHEAD_RANK 4
#define ADMIN_RANK 3
#define JADMIN_RANK 2
#define FRIEND_RANK 1
#define PLAYER_RANK 0
#define BANNED_PLAYER -1

// BASIC

#define BASIC_SKIN 55



#endif